# Generated by Django 6.0 on 2025-12-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('firm_type', models.CharField(choices=[('PE', 'Private Equity'), ('INDUSTRIAL_ROLLUP', 'Industrial Roll-Up'), ('INDUSTRIAL_SERVICES', 'Industrial Services'), ('SPECIALTY_MANUFACTURING', 'Specialty Manufacturing'), ('HEALTHCARE_ROLLUP', 'Healthcare Roll-Up'), ('HOLDCO', 'HoldCo'), ('DIVERSIFIED', 'Diversified')], max_length=50)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_targets', models.IntegerField(default=0)),
                ('succeeded_targets', models.IntegerField(default=0)),
                ('failed_targets', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='scraping_sc_status_ea1631_idx'), models.Index(fields=['created_at'], name='scraping_sc_created_2184f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, help_text='ROBOTS_BLOCKED, TIMEOUT, EXTRACTION_ERROR, etc.', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('retries', models.IntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scrape_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='scraping.scraperun')),
            ],
            options={
                'indexes': [models.Index(fields=['success'], name='scraping_sc_success_d03435_idx'), models.Index(fields=['error_type'], name='scraping_sc_error_t_59e4b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('permanently_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.firm')),
            ],
            options={
                'indexes': [models.Index(fields=['active'], name='scraping_se_active_b00223_idx'), models.Index(fields=['permanently_disabled'], name='scraping_se_permane_c66b44_idx')],
            },
        ),
    ]
