# Generated by Django 6.0 on 2025-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_type', models.CharField(choices=[('PE', 'Private Equity'), ('INDUSTRIAL_ROLLUP', 'Industrial Roll-Up'), ('INDUSTRIAL_SERVICES', 'Industrial Services'), ('SPECIALTY_MANUFACTURING', 'Specialty Manufacturing'), ('HEALTHCARE_ROLLUP', 'Healthcare Roll-Up'), ('HOLDCO', 'HoldCo'), ('DIVERSIFIED', 'Diversified')], max_length=50)),
                ('sector_tag', models.CharField(choices=[('INDUSTRIAL', 'Industrial'), ('HEALTHCARE', 'Healthcare'), ('FOOD_BEVERAGE', 'Food Beverage'), ('MANUFACTURING', 'Manufacturing'), ('SPECIALTY', 'Specialty'), ('OTHER', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField()),
                ('source_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('locations_count', models.IntegerField(blank=True, null=True)),
                ('real_estate_intensive', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
